name: Kognit
options:
  bundleIdPrefix: com.quyen244
settings:
  base:
    SWIFT_VERSION: "6.0"
    IPHONEOS_DEPLOYMENT_TARGET: "18.0"
    CODE_SIGNING_ALLOWED: NO
    CODE_SIGNING_REQUIRED: NO
    CODE_SIGN_IDENTITY: ""
targets:
  Kognit:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: Kognit
    info:
      path: Info.plist
